version: "3"

tasks:

  up:
    desc: "Subir todos os serviços com docker-compose"
    cmds:
      - docker compose up -d

  down:
    desc: "Derrubar todos os serviços"
    cmds:
      - docker compose down

  restart:
    desc: "Recriar containers e subir novamente"
    cmds:
      - docker compose down
      - docker compose build
      - docker compose up -d